name: todo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.5
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^4.0.3
  sqflite: ^2.2.4+1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.0+1
  rxdart: ^0.27.7
  date_picker_timeline: ^1.2.3
  timezone: ^0.9.1
  dbus: ^0.7.8
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/applogo.jpeg"


flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
    - images/applogo.jpeg
